# Generated by Django 4.1.4 on 2023-03-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_video_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_after_tranlated',
            name='mousaqe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mousaqe'),
        ),
    ]
