# Generated by Django 3.2.18 on 2023-03-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_citys_remove_mousaqe_address_earas_mousaqe_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mousaqe',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mousaqe',
            name='eara',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
