# Generated by Django 3.2.18 on 2023-03-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230325_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_after_tranlated',
            name='address',
        ),
    ]
