# Generated by Django 3.2.18 on 2023-03-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_mousaqe_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='mousaqeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, default=None, upload_to='pic')),
                ('mousaq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mousaqe')),
            ],
        ),
    ]
