# Generated by Django 3.2.18 on 2023-03-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_mousaqeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.file_after_tranlated')),
            ],
        ),
    ]
